# Generated by Django 4.2.3 on 2023-08-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
