# Generated by Django 4.2.3 on 2023-10-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_order_orderedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Фамилия имя'),
        ),
    ]
