# Generated by Django 4.2.3 on 2024-03-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
